import { Montserrat } from "next/font/google";
import "./styles.css";
import Header from "@/components/Header";
import { Container } from "@/components/Components.styled";
import Providers from "./providers";
import { ToastContainer } from "react-toastify";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Weather",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Container>
          <Header />
          <Providers>{children}</Providers>
          <ToastContainer />
        </Container>
      </body>
    </html>
  );
}
