import { Montserrat } from "next/font/google";
import "./styles.css";
import Header from "@/components/Header";
import { Container } from "@/components/Components.styled";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
